apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: review-handler
  name: review-handler
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: review-handler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: review-handler
    spec:
      containers:
        - image: ghcr.io/emil476m/gamebase-rh:0.0.37
          imagePullPolicy: IfNotPresent
          name: gamebase-rh
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
